# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "/tmp"

[build]
cmd = 'go build -gcflags "all=-N -l" -o /tmp/main'
full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec --continue /tmp/main"